// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHx2A3WK-3HhXlou4Hc_NJYU0MuLCLcPU',
    appId: '1:634498654868:web:db3814e55359d68e308a81',
    messagingSenderId: '634498654868',
    projectId: 'proyectofinalflutter-c6a11',
    authDomain: 'proyectofinalflutter-c6a11.firebaseapp.com',
    storageBucket: 'proyectofinalflutter-c6a11.firebasestorage.app',
    measurementId: 'G-CQZBGZM790',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxzXZZSt7GOY5qwCdJ9KbXVB93JFZiInA',
    appId: '1:634498654868:android:4ab5e45597e4e00c308a81',
    messagingSenderId: '634498654868',
    projectId: 'proyectofinalflutter-c6a11',
    storageBucket: 'proyectofinalflutter-c6a11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2tIyp3IHnnhd8VAk3sZ9cpERhTaoCTN8',
    appId: '1:634498654868:ios:84ea7a583edaf96a308a81',
    messagingSenderId: '634498654868',
    projectId: 'proyectofinalflutter-c6a11',
    storageBucket: 'proyectofinalflutter-c6a11.firebasestorage.app',
    androidClientId: '634498654868-7l3sganf3p0fs6c8vnke9msad930ulsf.apps.googleusercontent.com',
    iosClientId: '634498654868-28mq13cn5grfq0qbai87v9oig4iis1n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectofinalflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2tIyp3IHnnhd8VAk3sZ9cpERhTaoCTN8',
    appId: '1:634498654868:ios:84ea7a583edaf96a308a81',
    messagingSenderId: '634498654868',
    projectId: 'proyectofinalflutter-c6a11',
    storageBucket: 'proyectofinalflutter-c6a11.firebasestorage.app',
    androidClientId: '634498654868-7l3sganf3p0fs6c8vnke9msad930ulsf.apps.googleusercontent.com',
    iosClientId: '634498654868-28mq13cn5grfq0qbai87v9oig4iis1n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectofinalflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHx2A3WK-3HhXlou4Hc_NJYU0MuLCLcPU',
    appId: '1:634498654868:web:53966286c81e4d72308a81',
    messagingSenderId: '634498654868',
    projectId: 'proyectofinalflutter-c6a11',
    authDomain: 'proyectofinalflutter-c6a11.firebaseapp.com',
    storageBucket: 'proyectofinalflutter-c6a11.firebasestorage.app',
    measurementId: 'G-N2QNG1RWD5',
  );
}
